# Generated by Django 3.0.9 on 2025-10-03 10:57

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='Title of resource', max_length=255, verbose_name='Title')),
                ('is_template', models.BooleanField(default=False, help_text='Is a template', verbose_name='Is a template')),
                ('seen', models.BooleanField(default=False, help_text='Seen', verbose_name='Seen')),
                ('is_vault', models.BooleanField(default=False, help_text='Is in vault', verbose_name='Is in vault')),
                ('path', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, help_text='Materialized path of folder hierarchy', size=None, verbose_name='Path')),
                ('is_shared', models.BooleanField(default=False, help_text='Is folder shared between mediator and client', verbose_name='Is shared')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='folder', related_query_name='documents_folder', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', related_query_name='documents_folders', to='business.Matter', verbose_name='Matter')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='folders', related_query_name='documents_folders', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', related_query_name='documents_folders', to='documents.Folder', verbose_name='Parent')),
                ('shared_with', models.ManyToManyField(help_text='Users with which folder is shared', related_name='shared_folder', to=settings.AUTH_USER_MODEL, verbose_name='Shared with')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='Title of resource', max_length=255, verbose_name='Title')),
                ('is_template', models.BooleanField(default=False, help_text='Is a template', verbose_name='Is a template')),
                ('seen', models.BooleanField(default=False, help_text='Seen', verbose_name='Seen')),
                ('is_vault', models.BooleanField(default=False, help_text='Is in vault', verbose_name='Is in vault')),
                ('mime_type', models.CharField(help_text='Mime type of file', max_length=255, verbose_name='Mime type')),
                ('file', models.CharField(blank=True, help_text="Document's file", max_length=255, null=True, verbose_name='File')),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID', max_length=128, null=True, verbose_name='Transaction ID')),
                ('md5', models.CharField(blank=True, help_text='Transaction ID', max_length=100, null=True, verbose_name='md5sum')),
                ('uuid', models.UUIDField(default=uuid.uuid4, verbose_name='uuid')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document', related_query_name='documents_document', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('matter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', related_query_name='documents_documents', to='business.Matter', verbose_name='Matter')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', related_query_name='documents_documents', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', related_query_name='documents_documents', to='documents.Folder', verbose_name='Parent')),
                ('shared_with', models.ManyToManyField(help_text='Users with which document is shared', related_name='file', to=settings.AUTH_USER_MODEL, verbose_name='Shared with')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(matter__isnull=True), fields=('title', 'parent'), name='unique private root folder'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(parent__isnull=True), fields=('title', 'matter'), name='unique matter root folder'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('matter__isnull', True), ('parent__isnull', True)), fields=('title', 'owner'), name='unique root folder'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_shared', True), ('matter__isnull', False)), fields=('matter', 'is_shared'), name='unique shared folder for matter'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('is_template', True), ('owner__isnull', True), ('parent__isnull', True)), fields=('is_template',), name='unique root template folder'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, pk=django.db.models.expressions.F('parent')), name='parent can become parent to itself'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_shared', True), ('matter__isnull', False)), ('is_shared', False), _connector='OR'), name='shared folder must have matter'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('parent', 'title', 'owner', 'matter')},
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(matter__isnull=True), fields=('title', 'parent'), name='unique private root document'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('matter__isnull', True), ('parent__isnull', True)), fields=('title', 'owner'), name='unique root document'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('parent', 'title', 'owner', 'matter')},
        ),
    ]
