# Generated by Django 3.0.9 on 2025-10-03 10:56

import apps.users.models.users
import apps.users.validators
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('auth', '0011_update_proxy_permissions'),
        #('finance', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Used to make unique user unsubscribe link', unique=True, verbose_name='User uuid')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail address')),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=128, null=True, verbose_name='Phone')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('is_subscribed', models.BooleanField(default=True, help_text='Designates whether the user subscribe email notification', verbose_name='Subscribed')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Avatar')),
                ('twofa', models.BooleanField(default=False, verbose_name='Two Fator Authentication')),
                ('onboarding', models.BooleanField(default=False, verbose_name='Onboarding process')),
                ('is_free_subscription', models.BooleanField(default=False, verbose_name='The user is released from the subscription')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'AppUser',
                'verbose_name_plural': 'AppUsers',
            },
        ),
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Appointment Type',
                'verbose_name_plural': 'Appointment Type',
            },
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=3, unique=True, verbose_name='Currencies')),
            ],
            options={
                'verbose_name': 'Currencies',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('verification_status', django_fsm.FSMField(choices=[('not_verified', 'Not verified'), ('approved', 'Approved'), ('denied', 'Denied')], default='not_verified', max_length=20, verbose_name='Verification_status')),
                ('team_logo', models.CharField(blank=True, help_text='Firm logo', max_length=255, null=True, verbose_name='Firm logo')),
                ('role', models.CharField(help_text='Enterprise Role', max_length=20, verbose_name='Enterprise Role')),
                ('featured', models.BooleanField(default=False, verbose_name='Is featured')),
                ('firm_name', models.CharField(blank=True, help_text='Firm Name', max_length=100, null=True, verbose_name='Firm name')),
            ],
            options={
                'verbose_name': 'Enterprise',
                'verbose_name_plural': 'Enterprise',
            },
            bases=(apps.users.models.users.AppUserHelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FeeKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Fee Kind',
                'verbose_name_plural': 'Fee Kinds',
            },
        ),
        migrations.CreateModel(
            name='FirmSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=10, unique=True, verbose_name='Firmsize')),
            ],
            options={
                'verbose_name': 'Firmsize',
                'verbose_name_plural': 'Firmsize',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Language',
            },
        ),
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Law Firm',
                'verbose_name_plural': 'Law Firms',
            },
        ),
        migrations.CreateModel(
            name='MediatorRegistrationAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attachment', models.CharField(blank=True, help_text='Extra file attached by mediator on registration', max_length=255, null=True, verbose_name='Attachment file')),
            ],
            options={
                'verbose_name': "Mediator's registration attachment",
                'verbose_name_plural': "Mediator's registration attachments",
            },
        ),
        migrations.CreateModel(
            name='MediatorUniversity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Mediator University',
                'verbose_name_plural': 'Mediator Universities',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Enterprise member email address')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Payment Type',
                'verbose_name_plural': 'Payment Type',
            },
        ),
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.TextField(verbose_name='Timezone')),
            ],
            options={
                'verbose_name': 'Timezone',
                'verbose_name_plural': 'Timezones',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('client_type', models.CharField(choices=[('individual', 'Individual'), ('firm', 'Firm')], default='individual', help_text='Type of client', max_length=50, verbose_name='Type of client')),
                ('organization_name', models.CharField(blank=True, help_text='Name of organization', max_length=255, null=True, verbose_name='Name of organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='client', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('job', models.CharField(blank=True, help_text="Client's job title", max_length=128, null=True, verbose_name='Job')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('help_description', models.CharField(blank=True, help_text='What client is looking for help with', max_length=255, null=True, verbose_name='Needed help description')),
                ('zip_code', models.CharField(blank=True, help_text="Client's location(zip code)", max_length=10, null=True, verbose_name='zip code')),
                ('address1', models.CharField(blank=True, help_text="Client's location(address1)", max_length=50, null=True, verbose_name='Address1')),
                ('address2', models.CharField(blank=True, help_text="Client's location(address2)", max_length=50, null=True, verbose_name='Address2')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
            bases=(apps.users.models.users.AppUserHelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Mediator',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('verification_status', django_fsm.FSMField(choices=[('not_verified', 'Not verified'), ('approved', 'Approved'), ('denied', 'Denied')], default='not_verified', max_length=20, verbose_name='Verification_status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='mediator', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('featured', models.BooleanField(default=False, verbose_name='Is featured')),
                ('biography', models.TextField(blank=True, help_text="Mediator's legal pratice", null=True, verbose_name='Biography')),
                ('sponsored', models.BooleanField(default=False, help_text='Is mediator sponsored justmediation', verbose_name='Is sponsored')),
                ('sponsor_link', models.URLField(blank=True, help_text='Link to the sponsor of justmediation', null=True, verbose_name='Sponsor link')),
                ('firm_name', models.CharField(blank=True, help_text='Firm Name', max_length=100, null=True, verbose_name='Firm name')),
                ('website', models.URLField(blank=True, help_text='Firm website url', null=True, verbose_name='Firm website')),
                ('license_info', models.TextField(blank=True, help_text="Mediator's state, agency, date of admission and bar membership number", verbose_name='Licence info')),
                ('practice_description', models.TextField(blank=True, help_text="Description of mediator's legal practice (1000 characters)", max_length=1000, null=True, verbose_name='Practice description')),
                ('years_of_experience', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='How long has mediator been practicing')),
                ('have_speciality', models.BooleanField(default=True, help_text='Does mediator have speciality', verbose_name='Have speciality')),
                ('speciality_time', models.PositiveIntegerField(blank=True, help_text='Numbers of years practiced in specialized area', null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Speciality time')),
                ('speciality_matters_count', models.PositiveIntegerField(blank=True, help_text='Approximate number of matters in last 5 years, handled by mediator in specialized area', null=True, verbose_name='Speciality matters count')),
                ('fee_rate', models.DecimalField(decimal_places=2, default=None, help_text='How much mediator take per hour', max_digits=10, null=True, verbose_name='Fee rate')),
                ('extra_info', models.TextField(blank=True, help_text='Extra information about mediator', null=True, verbose_name='Extra information')),
                ('charity_organizations', models.TextField(blank=True, help_text='Name of any volunteer or charitable organizations mediator workwith or are member of', null=True, verbose_name='Charity organizations')),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Based on keywords, opportunities are formed for mediator', size=None, verbose_name='Keywords')),
                ('is_submittable_potential', models.BooleanField(default=False, help_text='Sumbit proposals for potential client engagments', verbose_name='Is Submittable Potential')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=None, help_text='Tax rate', max_digits=20, null=True, verbose_name='Tax rate')),
            ],
            options={
                'verbose_name': 'Mediator',
                'verbose_name_plural': 'Mediators',
            },
            bases=(apps.users.models.users.AppUserHelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('verification_status', django_fsm.FSMField(choices=[('not_verified', 'Not verified'), ('approved', 'Approved'), ('denied', 'Denied')], default='not_verified', max_length=20, verbose_name='Verification_status')),
                ('payment_status', django_fsm.FSMField(choices=[('not_started', 'Not started'), ('payment_in_progress', 'Payment in progress'), ('payment_failed', 'Payment failed'), ('paid', 'Paid')], default='not_started', help_text='Status of payment', max_length=30, verbose_name='Payment Status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='support', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('description', models.CharField(help_text="User's description (role)", max_length=128, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Other',
                'verbose_name_plural': 'Other users',
            },
            bases=(apps.users.models.users.AppUserHelperMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tag', models.CharField(choices=[('opportunities', 'Opportunities'), ('open_matter', 'Open matter'), ('referred_matter', 'Referred matter'), ('close_matter', 'Close matter'), ('active_lead', 'Active lead'), ('converted_lead', 'Converted lead')], help_text='Identifier of statistic', max_length=50, verbose_name='Tag')),
                ('count', models.PositiveIntegerField(default=1, help_text='Count', verbose_name='Count')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User statistics',
                'verbose_name_plural': 'User statistics',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speciality', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Speciality',
                'verbose_name_plural': 'Specialities',
            },
        ),
        migrations.CreateModel(
            name='MediatorIndustryContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_channel', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Chat channel ID')),
                ('industry_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Industry Contact')),
            ],
        ),
        migrations.CreateModel(
            name='MediatorEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('year', models.IntegerField(validators=[apps.users.validators.validate_activity_year], verbose_name='Year')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mediator_education', to='users.MediatorUniversity', verbose_name='University')),
            ],
            options={
                'verbose_name': "Mediator's education",
                'verbose_name_plural': "Mediators' education",
            },
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('agency', models.CharField(max_length=100, null=True, verbose_name='Agency')),
                ('number', models.CharField(max_length=20, null=True, verbose_name='Registeration number')),
                ('year', models.CharField(max_length=4, null=True, verbose_name='Admitted year')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurisdiction', to='cities_light.City', verbose_name='Jurisdiction city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurisdiction', to='cities_light.Country', verbose_name='Jurisdiction country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurisdiction', to='cities_light.Region', verbose_name='Jurisdiction state')),
            ],
            options={
                'verbose_name': 'Jurisdiction',
                'verbose_name_plural': 'Jurisdiction',
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('client_type', models.CharField(blank=True, choices=[('client', 'client'), ('lead', 'lead'), ('mediator', 'mediator')], help_text='Type of invitee', max_length=50, null=True, verbose_name='Type of invitee')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Primary key of invitation, used to make unique invitation link', primary_key=True, serialize=False, verbose_name='UUID')),
                ('user_type', models.CharField(choices=[('client', 'Client'), ('mediator', 'mediator'), ('lead', 'Lead')], default='client', max_length=10, verbose_name='Type of invited user')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('type', models.CharField(choices=[('imported', 'Imported'), ('invited_by_user', 'Invited by user')], default='invited_by_user', max_length=20, verbose_name='Type of invitation')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Middle name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail address')),
                ('message', models.TextField(blank=True, help_text='Message of invitation', null=True, verbose_name='Message')),
                ('sent', models.DateTimeField(blank=True, help_text='Time when invitation was sent', null=True, verbose_name='Sent at')),
                ('title', models.CharField(blank=True, help_text='Title', max_length=256, null=True, verbose_name='Title')),
                ('zip_code', models.CharField(blank=True, help_text="Invited contact's location(zip code)", max_length=10, null=True, verbose_name='zip code')),
                ('address', models.CharField(blank=True, help_text="Invited contact's location(address1)", max_length=100, null=True, verbose_name='Address1')),
                ('role', models.CharField(blank=True, help_text="Invited contact's job title", max_length=128, null=True, verbose_name='role')),
                ('help_description', models.CharField(blank=True, help_text='What client is looking for help with', max_length=255, null=True, verbose_name='Needed help description')),
                ('phone', models.CharField(blank=True, help_text="Invite's phone number", max_length=128, null=True, verbose_name='Phone')),
                ('organization_name', models.CharField(blank=True, help_text='Name of organization', max_length=255, null=True, verbose_name='Name of organization')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_city', to='cities_light.City', verbose_name='City')),
                ('country', models.ForeignKey(blank=True, help_text="Invited contact's country", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_country', to='cities_light.Country', verbose_name='Country')),
                ('inviter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Inviter')),
                ('shared_with', models.ManyToManyField(help_text='Users with which invitee is shared', related_name='shared_invitees', to=settings.AUTH_USER_MODEL, verbose_name='Shared with')),
                ('specialities', models.ManyToManyField(related_name='invites', to='users.Speciality', verbose_name='Specialities')),
                ('state', models.ForeignKey(blank=True, help_text="Invited contact's state", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_state', to='cities_light.Region', verbose_name='State')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
            },
        ),
        migrations.CreateModel(
            name='FirmLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('zip_code', models.CharField(max_length=20, verbose_name='ZipCode')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firm_location', to='cities_light.City', verbose_name='Firm city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firm_location', to='cities_light.Country', verbose_name='Firm country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firm_location', to='cities_light.Region', verbose_name='Firm state')),
            ],
            options={
                'verbose_name': 'FirmLocation',
                'verbose_name_plural': 'FirmLocation',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(choices=[('mediator', 'Mediator')], default='mediator', max_length=10, verbose_name='Type of member')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], default='pending', max_length=10, verbose_name='State of member')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Enterprise')),
                ('invitee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Member')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='enterprise',
            name='firm_locations',
            field=models.ManyToManyField(help_text="Country, State(s), Address(s), City(s), Zipcode of enterprise's Firm", related_name='enterprise', to='users.FirmLocation', verbose_name='Firm Location'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='firm_size',
            field=models.ForeignKey(blank=True, help_text='Firm size', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprise', to='users.FirmSize', verbose_name='Firm size'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='followers',
            field=models.ManyToManyField(related_name='followed_enterprise', to=settings.AUTH_USER_MODEL, verbose_name='Followers'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='team_members_invited',
            field=models.ManyToManyField(help_text='Email of enterprise members invited', related_name='enterprises', through='users.EnterpriseMembers', to='users.Member', verbose_name='Team Members Invited'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='team_members_registered',
            field=models.ManyToManyField(help_text='App User of enterprise members registered', related_name='enterprises', through='users.EnterpriseMembers', to=settings.AUTH_USER_MODEL, verbose_name='Team Members Registered'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='owned_enterprise', to=settings.AUTH_USER_MODEL, verbose_name='Enterprise Admin'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='specialities',
            field=models.ManyToManyField(related_name='users', to='users.Speciality', verbose_name='Specialities'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='timezone',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.TimeZone'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='userstatistic',
            index=models.Index(fields=['user', 'created'], name='users_users_user_id_2f83a1_idx'),
        ),
        migrations.AddField(
            model_name='support',
            name='payment',
            field=models.OneToOneField(blank=True, help_text='Link to payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support', related_query_name='users_support', to='finance.Payment', verbose_name='Payment'),
        ),
        migrations.AddField(
            model_name='mediatorregistrationattachment',
            name='mediator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_attachments', to='users.Mediator', verbose_name='Mediator'),
        ),
        migrations.AddField(
            model_name='mediatorindustrycontacts',
            name='mediator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Mediator', verbose_name='Mediator'),
        ),
        migrations.AddField(
            model_name='mediatoreducation',
            name='mediator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='education', to='users.Mediator', verbose_name='Mediator'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='appointment_type',
            field=models.ManyToManyField(blank=True, related_name='mediators', to='users.AppointmentType', verbose_name='AppointmentTypes'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediators', to='users.Enterprise', verbose_name='Enterprise'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='fee_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediators', to='users.Currencies', verbose_name='Fee Currency'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='fee_types',
            field=models.ManyToManyField(blank=True, related_name='mediators', to='users.FeeKind', verbose_name='FeeKinds'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='firm_locations',
            field=models.ManyToManyField(blank=True, help_text="Country, State(s), Address(s), City(s), Zipcode of mediator's Firm", related_name='mediators', to='users.FirmLocation', verbose_name='Firm Location'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_mediators', to=settings.AUTH_USER_MODEL, verbose_name='Followers'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='industry_contacts',
            field=models.ManyToManyField(blank=True, related_name='contacted_mediator', through='users.MediatorIndustryContacts', to=settings.AUTH_USER_MODEL, verbose_name='Industry Contacts'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='payment_type',
            field=models.ManyToManyField(blank=True, related_name='mediators', to='users.PaymentType', verbose_name='PaymentType'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='practice_jurisdictions',
            field=models.ManyToManyField(blank=True, help_text='Country, State(s), Agency(s) or federal jurisdiction mediator are licensed or authorised to practice in', related_name='mediators', to='users.Jurisdiction', verbose_name='Practice jurisdictions'),
        ),
        migrations.AddField(
            model_name='mediator',
            name='spoken_language',
            field=models.ManyToManyField(blank=True, related_name='mediators', to='users.Language', verbose_name='SpokenLanguages'),
        ),
        migrations.AddConstraint(
            model_name='invite',
            constraint=models.UniqueConstraint(fields=('email', 'inviter'), name='email_inviter_unique'),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='cities_light.City', verbose_name="Client's location(city)"),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='cities_light.Country', verbose_name="Client's location(country)"),
        ),
        migrations.AddField(
            model_name='client',
            name='favorite_mediators',
            field=models.ManyToManyField(help_text='Favorite mediator of client', related_name='clients', to='users.Mediator', verbose_name='favorite_mediators'),
        ),
        migrations.AddField(
            model_name='client',
            name='shared_with',
            field=models.ManyToManyField(help_text='Users with which client is shared', related_name='shared_clients', to=settings.AUTH_USER_MODEL, verbose_name='Shared with'),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='cities_light.Region', verbose_name="Client's location(state)"),
        ),
    ]
