# Generated by Django 3.0.9 on 2025-10-03 10:59

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorite')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('chat_channel', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Chat channel ID')),
                ('is_group', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Message Type')),
                ('timestamp1', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Message Text')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='social.Chats')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SingleChatParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Favorite')),
                ('appuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_chat_participants', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_chat_participants', to='social.Chats', verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.CharField(blank=True, help_text='Document file', max_length=255, null=True, verbose_name='File')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='File Title')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='social.Message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediatorPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='Post title', max_length=255, verbose_name='Title')),
                ('image', models.CharField(blank=True, help_text='Post Image', max_length=255, null=True, verbose_name='Post Image')),
                ('image_thumbnail', models.CharField(blank=True, help_text='Post Image', max_length=255, null=True, verbose_name='Post Image')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(help_text='Content of post', verbose_name='Body')),
                ('body_preview', models.TextField(help_text='Text preview of post', max_length=150, verbose_name='Preview')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='users.Mediator')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.AddField(
            model_name='chats',
            name='participants',
            field=models.ManyToManyField(related_name='chats', related_query_name='social_chatss', through='social.SingleChatParticipants', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
    ]
