# Generated by Django 3.0.9 on 2025-10-03 10:59

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='Title of notification', max_length=255, verbose_name='Title')),
                ('extra_payload', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Extra notification payload')),
                ('object_id', models.CharField(db_index=True, max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='Notification group title which will be displayed for the users', max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Notification group',
                'verbose_name_plural': 'Notification groups',
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('runtime_tag', models.CharField(help_text='Code related name of notification type', max_length=50, unique=True, verbose_name='Runtime tag')),
                ('title', models.CharField(help_text='Human-readable name of a type', max_length=100, verbose_name='Title')),
                ('is_for_client', models.BooleanField(default=False, help_text='Is notification type available for client', verbose_name='Is for client')),
                ('is_for_mediator', models.BooleanField(default=False, help_text='Is notification type available for mediator', verbose_name='Is for mediator')),
                ('is_for_enterprise', models.BooleanField(default=False, help_text='Is notification type available for enterprise', verbose_name='Is for enterprise')),
                ('is_for_other', models.BooleanField(default=False, help_text='Is notification type available for other', verbose_name='Is for other')),
                ('is_for_support', models.BooleanField(default=False, help_text='Is notification type available for support', verbose_name='Is for support')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types', to='notifications.NotificationGroup', verbose_name='Notification group')),
            ],
            options={
                'verbose_name': 'Notification type',
                'verbose_name_plural': 'Notification types',
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('by_email', models.BooleanField(default=True, help_text='Notify user by email', verbose_name='Notify by email')),
                ('by_push', models.BooleanField(default=True, help_text='Notify user by push notification', verbose_name='Notify by push notification')),
                ('by_chats', models.BooleanField(default=True, help_text='Notify user for chat', verbose_name='Notify for chat')),
                ('by_matters', models.BooleanField(default=True, help_text='Notify user for matter', verbose_name='Notify for matter')),
                ('by_forums', models.BooleanField(default=True, help_text='Notify user for forum', verbose_name='Notify for forum')),
                ('by_contacts', models.BooleanField(default=True, help_text='Notify user for contact', verbose_name='Notify for contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification setting',
                'verbose_name_plural': 'Notification settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationDispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', django_fsm.FSMField(choices=[('prepared', 'Prepared'), ('sent', 'Sent'), ('read', 'Read')], default='prepared', help_text='Notification status for recipient: prepared, sent, read', max_length=50, verbose_name='Status of notification')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_dispatches', to='notifications.Notification', verbose_name='Notification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_dispatches', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_dispatches_sender', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Notification dispatch',
                'verbose_name_plural': 'Notification dispatches',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='notifications.NotificationType', verbose_name='Notification type'),
        ),
    ]
